### ISSUE TITLE
if else parsing issue

### ISSUE THREAD

**Issue by CrazyFlasher** [innogames/ax3#10]
Such construction cannot be parsed
```
if (a == b)
  trace(1);
else
  trace(2);
```

**Comment by nadako** [comment]
This is a known parser limitation, similarly to unsupported ASI, the parser does not support semicolons at "arbitrary" places. It is recommended to wrap if/else and loop bodies into blocks to avoid issues like this.

Technically it's possiible to implement by adding token stacks and more lookahead, but we don't develop this project anymore, so feel free to do that in your own fork :)
