### ISSUE TITLE
No such package flash.display

### ISSUE THREAD

**Issue by quakeboy** [innogames/ax3#11]
Hey guys thank you for making this tool open-source, I'm getting back to game development after 6 years. I hope to revive my once released and flopped Flash game and try again with some new life into it.

---

I get the following errors. I'm keen about the last one - "No such package flash.display"
This is built-into flash how do I supply source code for it?

`../src/mykit/behaviours/FrameLoopBehaviour.as:18: character 15: Semicolon expected after block expression
../src/mykit/BasicInput.as:42: character 12: Semicolon expected after block expression
../src/mykit/utils/CoolFunctions.as:29: character 1: Semicolon expected after block expression
../src/mykit/ParticleSystem/ParticleEmitter.as:82: character 15: Semicolon expected after block expression
../src/mykit/ParticleSystem/ExplosionParticleSystem.as:66: character 9: Semicolon expected after block expression
../src/mykit/BasicSceneHolder.as:104: character 1: Semicolon expected after block expression
../src/mykit/BasicScene.as:46: character 26: Semicolon expected after block expression
../src/mykit/BasicThing.as:3: character 2: No such package flash.display
Exception in thread "main" assert
	at ax3.Typer$Closure_typeImports_0.invoke(src/ax3/Typer.hx:584)
	at ax3.Typer$Closure_typeImports_0.invoke(src/ax3/Typer.hx)
	at ax3.Typer$Closure_typeImports_0.invoke(src/ax3/Typer.hx:574)
	at ax3.Typer$Closure_typeImports_0.invoke(src/ax3/Typer.hx)
	at ax3.Typer.typeImports(src/ax3/Typer.hx:606)
	at ax3.Typer$Closure_processFile_0.invoke(src/ax3/Typer.hx:57)
	at ax3.Typer.process(src/ax3/Typer.hx:19)
	at ax3.Main.main(src/ax3/Main.hx:35)
	at ax3.Main.main(src/ax3/Main.hx:1)
`

**Comment by nadako** [comment]
Uhm, after these years I don't immediately remember, is there something unusual at `BasicThing.as:3`? Also did you add `swc` with playerglobal and stuff to the config, because the converter looks for types there as well.

**Comment by quakeboy** [comment]
@nadako thank you taking time to reply. I ended up using the haxelib package for the original tool - https://lib.haxe.org/p/as3hx. I kept getting this error related to flash packages no matter what I tried.
