### ISSUE TITLE
I think this project has been backdoored.

### ISSUE THREAD

**Issue by Buggem** [innogames/ax3#17]
Storing binary blobs in your code is a lil sussy behavior dont you think.

ඞ

**Comment by nadako** [comment]
what?

**Comment by Buggem** [comment]
https://github.com/innogames/ax3/blob/master/converter.jar
Binary blobs arent good for OSS, as they could store malware or anything really

**Comment by nadako** [comment]
Well, feel free to not use it and recompile, but I don't think it "has been backdoored". We committed the binary to the repo for the convenience back when AS3 porting was a hot topic, the project is provided as is and we're not really maintaining it anymore.
