### ISSUE TITLE
ASCompat.hx: openfl.Vector has no field isVector

### ISSUE THREAD

**Issue by fedor-strelkov** [innogames/ax3#4]
It seems that ASCompat.hx relies on a class function openfl.Vector.isVector() which doesn't exist in OpenFL:
compat/ASCompat.hx:171: characters 118-126 : openfl.Vector has no field isVector
compat/ASCompat.hx:172: characters 94-102 : openfl.Vector has no field isVector

**Comment by nadako** [comment]
Right, it relies on our own OpenFL fork which has this additional API: https://github.com/innogames/openfl/blob/54bd3a98a1d371bfb9d5160913c2093225a666d5/src/openfl/Vector.hx#L108. I forgot to add this to the README.

**Comment by fedor-strelkov** [comment]
Understood. It is definitely worth mentioning in the README that this converter relies on a special fork of OpenFL.

Anyway, the converter helped a lot in my case. Although I compiled the project based on the upstream OpenFL, I used ax3 output as a reference while doing manual code conversion.
